app:
  telegram-token: 6542454646:AAEaXmhljM2V2hOwMmZ0G69fjlM7o-csMjc

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
